socialappslab/appcivist-platform

app/Global.java
app/controllers/Application.java
app/controllers/Assemblies.java
app/controllers/AuthenticateLocal.java
app/controllers/Restricted.java
app/controllers/Secured.java
app/controllers/Users.java
app/controllers/WorkingGroups.java
app/http/Headers.java
conf/routes

Added support for CORS requests
Sources: 
- [Common headers](https://www.playframework.com/documentation/2.3.2/JavaActionsComposition) with [ActionComposition](https://www.playframework.com/documentation/2.3.2/JavaActionsComposition)
- Preflight request in [Global](https://www.evernote.com/l/ABiUu_f1-b9N6I-sfxpO4ORfsQqskt9deU8)

Develop: merged CORS support feature

---

app/models/Contribution.java

refs socialappslab/appcivist-platform#353
Fix sorting by popularity

Added popularity attribute to public view

---

app/controllers/Assemblies.java
app/controllers/Campaigns.java
app/controllers/Contributions.java
app/controllers/Memberships.java
app/controllers/Users.java
app/controllers/WorkingGroups.java
conf/routes

refs socialappslab/appcivist-platform#288
Review API Swagger Annotations

Change in swagger anotations

---

app/controllers/PasswordForgotChange.java
app/controllers/Users.java
app/models/User.java
app/providers/MyUsernamePasswordAuthProvider.java
app/utils/GlobalData.java
app/views/account/email/password_reset_de.scala.html
app/views/account/email/password_reset_de.scala.txt
app/views/account/email/password_reset_en.scala.html
app/views/account/email/password_reset_en.scala.txt
app/views/account/email/password_reset_es.scala.html
app/views/account/email/password_reset_es.scala.txt
app/views/account/email/password_reset_pl.scala.html
app/views/account/email/password_reset_pl.scala.txt
app/views/account/email/password_reset_pt.scala.html
app/views/account/email/password_reset_pt.scala.txt
app/views/profile.scala.html
conf/local.sample.conf
conf/routes

Unused endpoints deleted
Added email templates to send reset form
refs socialappslab/appcivist-platform#278
Review, test and rehabilitate (if needed) password forgot and change endpoints

New endpoint added for password forgot

---

app/controllers/ConfigValues.java
app/controllers/Configs.java
app/models/Config.java
conf/routes

refs socialappslab/appcivist-platform#341
Implement reading and updating configurations in a resource space

4 new endpoints for resource space configs was added

---

app/controllers/Assemblies.java

refs socialappslab/appcivist-platform#299
Add notifications calls also after PUT of assemblies

Added notification after put of assembly

---

app/controllers/Contributions.java

refs socialappslab/appcivist-platform#159
Contributions update issues

Put of contribution only edit first level attributes

---

app/controllers/Assemblies.java
app/models/Assembly.java
app/models/Organization.java
app/models/ResourceSpace.java
app/models/transfer/AssemblyTransfer.java
app/models/transfer/OrganizationTransfer.java
conf/evolutions/default/27.sql
conf/routes
conf/sql/database-create-postgres.sql

Endpoints GET-PUT-DELETE for organization in a resource space were added
refs socialappslab/appcivist-platform#365
Implement Organization model

New model Organization

---

app/controllers/Campaigns.java
conf/routes

refs socialappslab/appcivist-platform#367
Check the Assembly homepage design and comment what endpoints are needed for each piece of information

Endpoints GET-POST for resources in a resource space

---

app/controllers/Campaigns.java

refs socialappslab/appcivist-platform#358
Add endpoint to read resources of a resource space from anonymous site

Feature json configs

---

app/models/Assembly.java

refs socialappslab/appcivist-platform#392
Include assembly Id in GET assembly by shortname if the request had session key

Assembly id added to public view

---

app/controllers/Campaigns.java
conf/routes

refs socialappslab/appcivist-platform#384
Add template endpoints for the creation operations

Endpoints added for assembly and wg template json file

---

app/controllers/Spaces.java
conf/routes

refs socialappslab/appcivist-platform#410
Add public read endpoints for field values

New public endpoint to read field values by uuid

---

app/controllers/ResetConfig.java
app/controllers/Users.java
app/providers/MyUsernamePasswordAuthProvider.java

refs socialappslab/appcivist-platform#421
Frontend can define a base url for password reset

ConfigUrl parameter added to reset password endpoint

---

app/controllers/Contributions.java

refs socialappslab/appcivist-platform/issues/428

WG added in campaigns resource space

---

app/controllers/Campaigns.java
app/controllers/Spaces.java
conf/routes

refs socialappslab/appcivist-platform#424
PUT endpoints for Campaign and WG

Put endpoints for campaign y wg added

---

app/controllers/Contributions.java
build.sbt
conf/routes

refs socialappslab/appcivist-platform#415
Implement export proposal to PDF, RTF or CSV

Endpoint added to export proposal

---

app/controllers/Configs.java

refs socialappslab/appcivist-platform#442
Fix issue with update of configs

Bug fixed when update configs

---

conf/initial-data/appcivist-pb-sample-basic.yml
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#247
Membership roles are not cascaded when using models.MembershipGroup

Bug fixed in sample yml file

---

app/controllers/Campaigns.java
app/models/Campaign.java
app/models/CampaignTimelineEdge.java
app/models/Component.java

refs socialappslab/appcivist-platform#443
Bug: the backend is not updating component information

Bug fixed for update campign and components

---

app/controllers/Contributions.java
app/delegates/ContributionsDelegate.java
conf/routes

refs socialappslab/appcivist-platform#437
Add filter to get contributions in a space to list only contributions of an author by its id

Feature added to filter by author

---

app/models/User.java
app/providers/ExistingGroupSignupIdentity.java
app/providers/MyUsernamePasswordAuthProvider.java
app/providers/MyUsernamePasswordAuthUser.java

refs socialappslab/appcivist-platform#419
Implement Sign Up to Assembly

Feature added for support existing assembly for new user signup

---

test/NotificationTest.java

refs socialappslab/appcivist-platform#287
QA Testing and Review of Notifications

Test for notifications

---

app/controllers/Contributions.java
app/utils/Packager.java
conf/routes

refs socialappslab/appcivist-platform#416
Export a list of proposals in a resource space

List of proposals of the resource space in formats PDF/RTF/CSV

---

app/controllers/Spaces.java
app/models/Contribution.java
app/models/misc/ThemeStats.java
conf/routes

refs socialappslab/appcivist-platform#462
Add endpoint to return stats by Theme for a CAMPAGN, WG and PROPOSAL resource space

New endpoint for theme stats

---

app/controllers/Contributions.java
app/models/Contribution.java
conf/evolutions/default/35.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#460
New attributes for contribution model

New attribute cover added to contribution model

---

app/controllers/Contributions.java
app/delegates/ContributionsDelegate.java
conf/routes

refs socialappslab/appcivist-platform#463
Word Cloud Endpoint

New endpoint with the list of words and frequency

---

app/controllers/Spaces.java
app/models/CustomFieldValue.java
conf/routes

refs socialappslab/appcivist-platform#488
Custom Search Endpoint

New endpoint to search custom field values by value, space and definition

---

app/controllers/Configs.java
app/models/Assembly.java
app/security/MyDynamicResourceHandler.java
app/security/SecurityModelConstants.java
app/security/SpaceDynamicResourceHandler.java

refs socialappslab/appcivist-platform#434
Implementa access control for Coordinators of Group or Assembly associated to a Resource Space

Security model added for space

---

app/controllers/Contributions.java
app/models/Contribution.java
app/utils/GlobalDataConfigKeys.java

refs socialappslab/appcivist-platform#458
Verify and test contribution creation of both ideas and proposals

New Themes attributes for Contribution

---

app/delegates/ContributionsDelegate.java
app/models/Contribution.java
conf/evolutions/default/37.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#492
Updates to document creation on contributions

Document simple attribute added to contribution

---

app/controllers/Spaces.java
app/models/CustomFieldDefinition.java
app/models/CustomFieldValueOption.java
app/models/NonMemberAuthor.java
conf/evolutions/default/40.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#439
Custom Fields for Feedback: extend custom fields to support also scales, scores and multiple choices
Bug fixed on nonMemberAuthor class

Model CustomFieldValueOption added for customFieldDefinition endpoints

---

app/models/User.java
app/modules/CustomDeadboltHook.java
app/service/PlayAuthenticateLocal.java
app/service/facebook/FacebookAuthInfoLocal.java
app/service/facebook/FacebookAuthProviderLocal.java
app/service/facebook/FacebookAuthUserLocal.java
conf/play-authenticate/mine.conf.sample
conf/play.plugins

refs socialappslab/appcivist-platform#182
Add authentication with Google and Facebook

Support for google and facebook login added

---

app/controllers/Campaigns.java
app/models/Campaign.java
app/models/transfer/CampaignTransfer.java
conf/evolutions/default/41.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#507
Add cover to campaign model

Cover attribute added to campaign model

---

app/models/WorkingGroupProfile.java
app/utils/GlobalData.java
conf/evolutions/default/43.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#343
Add color to Working Group model

Attribute color added with default value

---

app/Global.java
build.sbt

refs socialappslab/appcivist-platform#510
Implement a scheduler for notifications
TODO add service newsletter to scheduler

Schedule added for not sented signals

---

app/models/Campaign.java
conf/evolutions/default/42.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#522
Add Logo to campaign model

Attribute logo added to campaign model

---

app/controllers/Contributions.java

refs socialappslab/appcivist-platform#532
Emergent themes must be added to the containing Campaign or WG

Themes associated to the containing resource space of wg or campaign

---

conf/evolutions/default/46.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#513
Refactor simple document ts_vectors to remove stop words

Changes for stop words in contributions

---

app/controllers/Contributions.java
app/enums/ContributionStatus.java
conf/evolutions/default/45.sql
conf/sql/database-create-postgres.sql

refs socialappslab/appcivist-platform#514
Replace contribution status NEW per DRAFT

Enum of contribution status changed NEW to DRAFT

---

app/controllers/Spaces.java
conf/routes

refs socialappslab/appcivist-platform#537
Implement endpoint to GET non-member-authors connected to contributions of a campaign, with all their custom fields

Endpoint added for nonMemberAuthor csv export

---

app/models/Contribution.java
app/models/ContributionFeedback.java

Transient atributes containingContributionsIds and parentType added to Contribution and ContributionFeedback models respectively

Transient attributes added for social ideation integration

---

app/models/Contribution.java

Bug fixed when no containing contribution is found for containingContribution Transient attribute

ContainingContribution Bug fixed

---

app/controllers/Locations.java
app/controllers/WorkingGroups.java
app/models/WorkingGroup.java
app/models/location/Location.java
app/utils/GlobalData.java
app/utils/services/NominatimWrapper.java
conf/evolutions/default/47.sql
conf/routes

**local.conf** configuration:
```
services {
geocoding.service = "nominatim"
}
```
1. Nominatim wrapper endpoint: `/api/location/geojson/:query`
2. Update all locations endpoint: `/api/location/update/geojson` 
(In both cases, placeName is used as nominatim search param)
3. Search working group by location name endpoint:  `/api/assembly/:aid/group/location/:location_name`

Feature 536

---

app/controllers/Contributions.java
app/delegates/ContributionsDelegate.java

Check social ideation headers for assign author  when creating a contribution that comes from a social network

Check social ideation headers for assign author 

---

app/delegates/NotificationsDelegate.java
app/enums/UserProfileConfigsTypes.java
app/models/Assembly.java

Creating notificationEventSignalUser to All members of the Assembly that owns the parent campaign, with and auto-subscribe configuration set to TRUE (if the spaceType is CAMPAIGN)

Feature 610

---

app/models/User.java

Fix error on creating user membership on existing assembly on user signup

---

app/controllers/Assemblies.java

Add the case: If send_invitations == TRUE, memberships are created with status INVITED

Upload member endpoints update

---

app/controllers/Notifications.java
app/delegates/NotificationsDelegate.java
conf/routes

Adds type parameter to user notification and user notification stats
services

Update User Notification endpoints

---

app/controllers/Assemblies.java
app/controllers/Contributions.java
app/controllers/WorkingGroups.java
app/models/Subscription.java

Check each case for ensure the expected functionality

Add auto subscription for new members

---

app/delegates/NotificationsDelegate.java
app/models/Component.java
app/providers/MyUsernamePasswordAuthProvider.java
app/schedulers/NewsletterCreatorSchedule.java
app/service/BusComponent.java
build.sbt
conf/local.sample.conf
conf/newsletters-templates/newsletter-backend-template-no-activity.html
conf/newsletters-templates/newsletter-backend-template-proposal-stage.html
conf/newsletters-templates/newsletter-backend-template-with-activity.html
docs/rabbitmq_messages.md

Add send signals direct to the rabbitmq
Confs add:
```
appcivist {
rabbitmq {
host = "localhost"
port = 5672
user = "guest"
password = "guest"
exchange = "appcivist"
active = true
}
newsletter {
unsuscribeUrl = ""
}
}
```

Feature/15 - Rabbitmq signals

---

app/controllers/Contributions.java
app/delegates/ContributionsDelegate.java

No need to grant permissions to social ideation from appcivist interface anymore.

new social ideation header added: 'social_ideation_email'

---

app/controllers/Contributions.java

- Add more logging
- Support case insensitive formats
- Change export by id to not use flatten json

Export contributions improvements

---

app/controllers/Assemblies.java
app/models/MembershipInvitation.java
app/models/transfer/InvitationTransfer.java

- Include EXPERT role
- Change the use of hand parsing csv for CsvReader

Changes in MEMBERs csv import
